version: '3.8'
name: ingressify

services:

  db-ingressify:
    container_name: ingressify-db-ingressify
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ingressify
      - POSTGRES_PASSWORD=ingressify
      - POSTGRES_DB=ingressify
    volumes:
      - $VOLUME/postgres/ingressify/data:/var/lib/postgresql/data
    restart: always
    networks:
      - private-network
  
  prometheus:
    image: prom/prometheus:latest
    container_name: ingressify-prometheus
    ports:
      - 9090:9090
    volumes:
      - $VOLUME/prometheus:/etc/prometheus
      - $VOLUME/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - private-network

  grafana:
    container_name: ingressify-grafana
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - $VOLUME/grafana:/var/lib/grafana
      - $VOLUME/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources      
    restart: always
    networks:
      - private-network

  discovery:
    build:
      context: ../ingressify.discovery/
      dockerfile: Dockerfile
    container_name: ingressify-discovery
    image: ingressify-discovery:latest
    ports:
      - 8761:8761
    restart: always
    networks:
      - private-network

  gateway:
    build:
      context: ../ingressify.gateway/
      dockerfile: Dockerfile
    container_name: ingressify-gateway
    image: ingressify-gateway:latest
    ports:
      - 8080:8080
    environment:
      - eureka.client.service-url.defaultZone=http://ingressify-discovery:8761/eureka/
    networks:
      - private-network
    depends_on:
      - discovery

  account:
    build: 
      context: ../ingressify.account-resource/
      dockerfile: Dockerfile
    container_name: ingressify-account
    image: ingressify-account:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://ingressify-db-ingressify:5432/ingressify
      - spring.datasource.username=ingressify
      - spring.datasource.password=ingressify
      - eureka.client.service-url.defaultZone=http://ingressify-discovery:8761/eureka

    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private-network
    depends_on:
      - db-ingressify
      - discovery

  auth:
    build:
      context: ../ingressify.auth-resource/
      dockerfile: Dockerfile
    container_name: ingressify-auth
    image: ingressify-auth:latest
    ports:
      - 8080:8080
    environment:
      - eureka.client.service-url.defaultZone=http://ingressify-discovery:8761/eureka/
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - private-network
    depends_on:
      - discovery
      - account

networks:
  private-network:
    driver: bridge