version: '3.8'
name: ingressify

services:

  db-ingressify:
    container_name: ingressify-db-ingressify
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ingressify
      - POSTGRES_PASSWORD=ingressify
      - POSTGRES_DB=ingressify
    volumes:
      - $VOLUME/postgres/ingressify/data:/var/lib/postgresql/data
    restart: always
    networks:
      - private-network

  discovery:
    build:
      context: ../ingressify.discovery/
      dockerfile: Dockerfile
    image: ingressify-discovery:latest
    ports:
      - 8761:8761
    environment:
      - spring.datasource.url=jdbc:postgresql://ingressify-db-ingressify:5432/ingressify
      - spring.datasource.username=ingressify
      - spring.datasource.password=ingressify
    restart: always
    networks:
      - private-network

  account:
    build:
      context: ../mcs.account-resource/
      dockerfile: Dockerfile
    container_name: ingressify-account
    image: ingressify-account:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://ingressify-db-ingressify:5432/ingressify
      - spring.datasource.username=ingressify
      - spring.datasource.password=ingressify
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private-network
    depends_on:
      - db-ingressify
      - discovery

networks:
  private-network:
    driver: bridge